### ISSUE TITLE
Still can't load new demo data

### ISSUE THREAD

**Issue by wingz1** [danyang-liu/KRED#5]
Thanks for updating the demo data.  I pulled the repo again, unzipped the new demo data, but still can't get the demo to work as advertised.

KRED]$ python main.py --rootpath ./demo/
constructing adjacency matrix ...
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    main()
  File "main.py", line 33, in main
    data = load_data(args)
  File ".../KRED/utils/data_loader.py", line 265, in load_data
    entity_adj, relation_adj = construct_adj(graph_file, entity2id_file, args)
  File ".../KRED/utils/data_loader.py", line 37, in construct_adj
    entity_adj[int(key)].append(int(kg[key][i][0]))
IndexError: list index out of range

Thanks for any help!

**Comment by danyang-liu** [comment]
sorry for this, fix the bug.
